trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-unbuntu-docker'
  buildNumber: $(Date:yyyyMMdd)$(Rev:.r)


stages:
- stage: DockerUnbuntuImage
  jobs:
  - job: SpoolUnbuntoImage
    steps: 

  - job: CreateBuildDirectory
    steps:    
    - bash: if [ ! -d "/var/www/html/versions/<env>.<buildNumber>" ]; then
            mkdir /var/www/html/versions/<env>.<buildNumber>
            fi


    # task: Docker@2
    # displayName: Build an image
    # inputs:
    #   repository: $(imageName)
    #   command: build
    #   Dockerfile: app/Dockerfile
    
    - script: echo Creating Directory for build!





    
- stage: DeployToUnbuntuImage
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!



