trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-unbuntu-docker'
  buildNumber: $(Date:yyyyMMdd)$(Rev:.r)


stages:
- stage: DockerUnbuntuImage
  jobs:
  - job: SpoolUnbuntuImage
    steps: 
    - bash:     
    # task: Docker@2
    # displayName: Build an image
    # inputs:
    #   repository: $(imageName)
    #   command: build
    #   Dockerfile: app/Dockerfile

- stage: DeployDirectories
  jobs:
  - job: CreateDeployDirectory
    steps:    
    - bash: if [ ! -d "/var/www/html/versions/<env>.<buildNumber>" ]; then
            mkdir /var/www/html/versions/<env>.<buildNumber>
            fi

    - script: echo Creating Directory for build!

  - job: UnpackFilesForWebServer
    steps:
    - bash: unzip <zipfile> -d /var/www/html/versions/<env>.<buildNumber>/
            mv /var/www/html/versions/<env>.<buildNumber>/settings/banks.<env>.json /var/www/html/versions/<env>.<buildNumber>/settings/banks.json 
            rm -f /var/www/html/versions/<env>.<buildNumber>/settings/banks.*.json
            chgrp -R deployment /var/www/html/versions/<env>.<buildNumber>/
            chmod 770 /var/www/html/versions/<env>.<buildNumber>/cache
    - script: Unpacking Web Server Files!

- stage: PointWebServerToRelease
  jobs:
  - job: PointWebServer
    steps:
    - bash: rm /var/www/html/versions/current
            ln -s /var/www/html/versions/<env>.<buildNumber>/var/www/html/versions/current

    - script: Pointing Web Server to Current Release!


- stage: DBServerBackup
  jobs:
  - job: DBBackup
    steps:
    - bash: /opt/bim/backups/bin/dbbimapi_backup.sh

    - script: Backing Up DB Server!



